name: Check Upstream Tags

on:
  schedule:
    - cron: 12 4 * * *
  workflow_dispatch:

jobs:
  check_upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Upstream Tags
        uses: actions/github-script@v6
        id: tags
        with:
          script: |
            const script = require('./scripts/workflows/tags.js')
            await script({github, context, core})
      - name: Call Build
        uses: actions/github-script@v6
        id: call_build
        env:
          TAGS: ${{ steps.tags.outputs.result }}
        with:
          script: |
            const { TAGS } = process.env
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yml',
              ref: 'main',
              inputs: { tags: TAGS }
            })
