name: Check Upstream

on:
  schedule:
    - cron: 12 4 * * *
  workflow_dispatch:

jobs:
  check_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Get Upstream Tags
        uses: actions/github-script@v6
        id: tags
        with:
          script: |
            console.log('started');
            const refs = await github.git.listMatchingRefs({
              owner: 'nzbget-ng',
              repo: 'nzbget',
              ref: 'tags'
              });
            console.log(refs);
            const shas = refs.map(x => x.object.sha);
            console.log(shas);
            var tags = [];
            shas.forEach(() => {
              const ref = await github.rest.git.getTag({
                owner: 'nzbget-ng',
                repo: 'nzbget',
                tag_sha: this
              });
              console.log(ref);
              const msPerDay = 24 * 60 * 60 * 1000;
              if (Date.now()-Date.Parse(ref.tagger.date)/msPerDay < 30)
                tags.push(ref.tag);
            })
            console.log(tags);
            return tags;
          result-encoding: string
      - name: Call Build
        uses: actions/github-script@v6
        id: call_build
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yml',
              ref: 'main',
              inputs: {
                tags: ${{ steps.tags.outputs.result }}
              }
            })
